/*! URI.js v1.16.0 http://medialize.github.io/URI.js/ */
/* build contains: URI.js, URITemplate.js, URI.fragmentQuery.js */
(function(f,n){"object"===typeof exports?module.exports=n(require("./punycode"),require("./IPv6"),require("./SecondLevelDomains")):"function"===typeof define&&define.amd?define(["./punycode","./IPv6","./SecondLevelDomains"],n):f.URI=n(f.punycode,f.IPv6,f.SecondLevelDomains,f)})(this,function(f,n,q,t){function c(a,b){var d=1<=arguments.length,k=2<=arguments.length;if(!(this instanceof c))return d?k?new c(a,b):new c(a):new c;if(void 0===a){if(d)throw new TypeError("undefined is not a valid argument for URI");
a="undefined"!==typeof location?location.href+"":""}this.href(a);return void 0!==b?this.absoluteTo(b):this}function x(a){return a.replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")}function h(a){return void 0===a?"Undefined":String(Object.prototype.toString.call(a)).slice(8,-1)}function l(a){return"Array"===h(a)}function g(a,b){var d={},c,w;if("RegExp"===h(b))d=null;else if(l(b))for(c=0,w=b.length;c<w;c++)d[b[c]]=!0;else d[b]=!0;c=0;for(w=a.length;c<w;c++)if(d&&void 0!==d[a[c]]||!d&&b.test(a[c]))a.splice(c,
1),w--,c--;return a}function r(a,b){var d,c;if(l(b)){d=0;for(c=b.length;d<c;d++)if(!r(a,b[d]))return!1;return!0}var w=h(b);d=0;for(c=a.length;d<c;d++)if("RegExp"===w){if("string"===typeof a[d]&&a[d].match(b))return!0}else if(a[d]===b)return!0;return!1}function z(a,b){if(!l(a)||!l(b)||a.length!==b.length)return!1;a.sort();b.sort();for(var d=0,c=a.length;d<c;d++)if(a[d]!==b[d])return!1;return!0}function D(a){return escape(a)}function A(a){return encodeURIComponent(a).replace(/[!'()*]/g,D).replace(/\*/g,
"%2A")}function y(a){return function(b,d){if(void 0===b)return this._parts[a]||"";this._parts[a]=b||null;this.build(!d);return this}}function p(a,b){return function(d,c){if(void 0===d)return this._parts[a]||"";null!==d&&(d+="",d.charAt(0)===b&&(d=d.substring(1)));this._parts[a]=d;this.build(!c);return this}}var m=t&&t.URI;c.version="1.16.0";var e=c.prototype,v=Object.prototype.hasOwnProperty;c._parts=function(){return{protocol:null,username:null,password:null,hostname:null,urn:null,port:null,path:null,
query:null,fragment:null,duplicateQueryParameters:c.duplicateQueryParameters,escapeQuerySpace:c.escapeQuerySpace}};c.duplicateQueryParameters=!1;c.escapeQuerySpace=!0;c.protocol_expression=/^[a-z][a-z0-9.+-]*$/i;c.idn_expression=/[^a-z0-9\.-]/i;c.punycode_expression=/(xn--)/i;c.ip4_expression=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;c.ip6_expression=/^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$/;
c.find_uri_expression=/\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))/ig;c.findUri={start:/\b(?:([a-z][a-z0-9.+-]*:\/\/)|www\.)/gi,end:/[\s\r\n]|$/,trim:/[`!()\[\]{};:'".,<>?\u00ab\u00bb\u201c\u201d\u201e\u2018\u2019]+$/};c.defaultPorts={http:"80",https:"443",ftp:"21",gopher:"70",ws:"80",wss:"443"};c.invalid_hostname_characters=
/[^a-zA-Z0-9\.-]/;c.domAttributes={a:"href",blockquote:"cite",link:"href",base:"href",script:"src",form:"action",img:"src",area:"href",iframe:"src",embed:"src",source:"src",track:"src",input:"src",audio:"src",video:"src"};c.getDomAttribute=function(a){if(a&&a.nodeName){var b=a.nodeName.toLowerCase();return"input"===b&&"image"!==a.type?void 0:c.domAttributes[b]}};c.encode=A;c.decode=decodeURIComponent;c.iso8859=function(){c.encode=escape;c.decode=unescape};c.unicode=function(){c.encode=A;c.decode=
decodeURIComponent};c.characters={pathname:{encode:{expression:/%(24|26|2B|2C|3B|3D|3A|40)/ig,map:{"%24":"$","%26":"&","%2B":"+","%2C":",","%3B":";","%3D":"=","%3A":":","%40":"@"}},decode:{expression:/[\/\?#]/g,map:{"/":"%2F","?":"%3F","#":"%23"}}},reserved:{encode:{expression:/%(21|23|24|26|27|28|29|2A|2B|2C|2F|3A|3B|3D|3F|40|5B|5D)/ig,map:{"%3A":":","%2F":"/","%3F":"?","%23":"#","%5B":"[","%5D":"]","%40":"@","%21":"!","%24":"$","%26":"&","%27":"'","%28":"(","%29":")","%2A":"*","%2B":"+","%2C":",",
"%3B":";","%3D":"="}}},urnpath:{encode:{expression:/%(21|24|27|28|29|2A|2B|2C|3B|3D|40)/ig,map:{"%21":"!","%24":"$","%27":"'","%28":"(","%29":")","%2A":"*","%2B":"+","%2C":",","%3B":";","%3D":"=","%40":"@"}},decode:{expression:/[\/\?#:]/g,map:{"/":"%2F","?":"%3F","#":"%23",":":"%3A"}}}};c.encodeQuery=function(a,b){var d=c.encode(a+"");void 0===b&&(b=c.escapeQuerySpace);return b?d.replace(/%20/g,"+"):d};c.decodeQuery=function(a,b){a+="";void 0===b&&(b=c.escapeQuerySpace);try{return c.decode(b?a.replace(/\+/g,
"%20"):a)}catch(d){return a}};var u={encode:"encode",decode:"decode"},B,C=function(a,b){return function(d){try{return c[b](d+"").replace(c.characters[a][b].expression,function(d){return c.characters[a][b].map[d]})}catch(k){return d}}};for(B in u)c[B+"PathSegment"]=C("pathname",u[B]),c[B+"UrnPathSegment"]=C("urnpath",u[B]);u=function(a,b,d){return function(k){var w;w=d?function(a){return c[b](c[d](a))}:c[b];k=(k+"").split(a);for(var e=0,g=k.length;e<g;e++)k[e]=w(k[e]);return k.join(a)}};c.decodePath=
u("/","decodePathSegment");c.decodeUrnPath=u(":","decodeUrnPathSegment");c.recodePath=u("/","encodePathSegment","decode");c.recodeUrnPath=u(":","encodeUrnPathSegment","decode");c.encodeReserved=C("reserved","encode");c.parse=function(a,b){var d;b||(b={});d=a.indexOf("#");-1<d&&(b.fragment=a.substring(d+1)||null,a=a.substring(0,d));d=a.indexOf("?");-1<d&&(b.query=a.substring(d+1)||null,a=a.substring(0,d));"//"===a.substring(0,2)?(b.protocol=null,a=a.substring(2),a=c.parseAuthority(a,b)):(d=a.indexOf(":"),
-1<d&&(b.protocol=a.substring(0,d)||null,b.protocol&&!b.protocol.match(c.protocol_expression)?b.protocol=void 0:"//"===a.substring(d+1,d+3)?(a=a.substring(d+3),a=c.parseAuthority(a,b)):(a=a.substring(d+1),b.urn=!0)));b.path=a;return b};c.parseHost=function(a,b){a=a.replace(/\\/g,"/");var d=a.indexOf("/"),c;-1===d&&(d=a.length);if("["===a.charAt(0))c=a.indexOf("]"),b.hostname=a.substring(1,c)||null,b.port=a.substring(c+2,d)||null,"/"===b.port&&(b.port=null);else{var w=a.indexOf(":");c=a.indexOf("/");
w=a.indexOf(":",w+1);-1!==w&&(-1===c||w<c)?(b.hostname=a.substring(0,d)||null,b.port=null):(c=a.substring(0,d).split(":"),b.hostname=c[0]||null,b.port=c[1]||null)}b.hostname&&"/"!==a.substring(d).charAt(0)&&(d++,a="/"+a);return a.substring(d)||"/"};c.parseAuthority=function(a,b){a=c.parseUserinfo(a,b);return c.parseHost(a,b)};c.parseUserinfo=function(a,b){var d=a.indexOf("/"),k=a.lastIndexOf("@",-1<d?d:a.length-1);-1<k&&(-1===d||k<d)?(d=a.substring(0,k).split(":"),b.username=d[0]?c.decode(d[0]):null,
d.shift(),b.password=d[0]?c.decode(d.join(":")):null,a=a.substring(k+1)):(b.username=null,b.password=null);return a};c.parseQuery=function(a,b){if(!a)return{};a=a.replace(/&+/g,"&").replace(/^\?*&*|&+$/g,"");if(!a)return{};for(var d={},k=a.split("&"),w=k.length,e,g,r=0;r<w;r++)if(e=k[r].split("="),g=c.decodeQuery(e.shift(),b),e=e.length?c.decodeQuery(e.join("="),b):null,v.call(d,g)){if("string"===typeof d[g]||null===d[g])d[g]=[d[g]];d[g].push(e)}else d[g]=e;return d};c.build=function(a){var b="";
a.protocol&&(b+=a.protocol+":");a.urn||!b&&!a.hostname||(b+="//");b+=c.buildAuthority(a)||"";"string"===typeof a.path&&("/"!==a.path.charAt(0)&&"string"===typeof a.hostname&&(b+="/"),b+=a.path);"string"===typeof a.query&&a.query&&(b+="?"+a.query);"string"===typeof a.fragment&&a.fragment&&(b+="#"+a.fragment);return b};c.buildHost=function(a){var b="";if(a.hostname)b=c.ip6_expression.test(a.hostname)?b+("["+a.hostname+"]"):b+a.hostname;else return"";a.port&&(b+=":"+a.port);return b};c.buildAuthority=
function(a){return c.buildUserinfo(a)+c.buildHost(a)};c.buildUserinfo=function(a){var b="";a.username&&(b+=c.encode(a.username),a.password&&(b+=":"+c.encode(a.password)),b+="@");return b};c.buildQuery=function(a,b,d){var k="",e,g,r,f;for(g in a)if(v.call(a,g)&&g)if(l(a[g]))for(e={},r=0,f=a[g].length;r<f;r++)void 0!==a[g][r]&&void 0===e[a[g][r]+""]&&(k+="&"+c.buildQueryParameter(g,a[g][r],d),!0!==b&&(e[a[g][r]+""]=!0));else void 0!==a[g]&&(k+="&"+c.buildQueryParameter(g,a[g],d));return k.substring(1)};
c.buildQueryParameter=function(a,b,d){return c.encodeQuery(a,d)+(null!==b?"="+c.encodeQuery(b,d):"")};c.addQuery=function(a,b,d){if("object"===typeof b)for(var k in b)v.call(b,k)&&c.addQuery(a,k,b[k]);else if("string"===typeof b)void 0===a[b]?a[b]=d:("string"===typeof a[b]&&(a[b]=[a[b]]),l(d)||(d=[d]),a[b]=(a[b]||[]).concat(d));else throw new TypeError("URI.addQuery() accepts an object, string as the name parameter");};c.removeQuery=function(a,b,d){var k;if(l(b))for(d=0,k=b.length;d<k;d++)a[b[d]]=
void 0;else if("RegExp"===h(b))for(k in a)b.test(k)&&(a[k]=void 0);else if("object"===typeof b)for(k in b)v.call(b,k)&&c.removeQuery(a,k,b[k]);else if("string"===typeof b)void 0!==d?"RegExp"===h(d)?!l(a[b])&&d.test(a[b])?a[b]=void 0:a[b]=g(a[b],d):a[b]===d?a[b]=void 0:l(a[b])&&(a[b]=g(a[b],d)):a[b]=void 0;else throw new TypeError("URI.removeQuery() accepts an object, string, RegExp as the first parameter");};c.hasQuery=function(a,b,d,k){if("object"===typeof b){for(var e in b)if(v.call(b,e)&&!c.hasQuery(a,
e,b[e]))return!1;return!0}if("string"!==typeof b)throw new TypeError("URI.hasQuery() accepts an object, string as the name parameter");switch(h(d)){case "Undefined":return b in a;case "Boolean":return a=Boolean(l(a[b])?a[b].length:a[b]),d===a;case "Function":return!!d(a[b],b,a);case "Array":return l(a[b])?(k?r:z)(a[b],d):!1;case "RegExp":return l(a[b])?k?r(a[b],d):!1:Boolean(a[b]&&a[b].match(d));case "Number":d=String(d);case "String":return l(a[b])?k?r(a[b],d):!1:a[b]===d;default:throw new TypeError("URI.hasQuery() accepts undefined, boolean, string, number, RegExp, Function as the value parameter");
}};c.commonPath=function(a,b){var d=Math.min(a.length,b.length),c;for(c=0;c<d;c++)if(a.charAt(c)!==b.charAt(c)){c--;break}if(1>c)return a.charAt(0)===b.charAt(0)&&"/"===a.charAt(0)?"/":"";if("/"!==a.charAt(c)||"/"!==b.charAt(c))c=a.substring(0,c).lastIndexOf("/");return a.substring(0,c+1)};c.withinString=function(a,b,d){d||(d={});var k=d.start||c.findUri.start,e=d.end||c.findUri.end,g=d.trim||c.findUri.trim,r=/[a-z0-9-]=["']?$/i;for(k.lastIndex=0;;){var f=k.exec(a);if(!f)break;f=f.index;if(d.ignoreHtml){var m=
a.slice(Math.max(f-3,0),f);if(m&&r.test(m))continue}var m=f+a.slice(f).search(e),p=a.slice(f,m).replace(g,"");d.ignore&&d.ignore.test(p)||(m=f+p.length,p=b(p,f,m,a),a=a.slice(0,f)+p+a.slice(m),k.lastIndex=f+p.length)}k.lastIndex=0;return a};c.ensureValidHostname=function(a){if(a.match(c.invalid_hostname_characters)){if(!f)throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-] and Punycode.js is not available');if(f.toASCII(a).match(c.invalid_hostname_characters))throw new TypeError('Hostname "'+
a+'" contains characters other than [A-Z0-9.-]');}};c.noConflict=function(a){if(a)return a={URI:this.noConflict()},t.URITemplate&&"function"===typeof t.URITemplate.noConflict&&(a.URITemplate=t.URITemplate.noConflict()),t.IPv6&&"function"===typeof t.IPv6.noConflict&&(a.IPv6=t.IPv6.noConflict()),t.SecondLevelDomains&&"function"===typeof t.SecondLevelDomains.noConflict&&(a.SecondLevelDomains=t.SecondLevelDomains.noConflict()),a;t.URI===this&&(t.URI=m);return this};e.build=function(a){if(!0===a)this._deferred_build=
!0;else if(void 0===a||this._deferred_build)this._string=c.build(this._parts),this._deferred_build=!1;return this};e.clone=function(){return new c(this)};e.valueOf=e.toString=function(){return this.build(!1)._string};e.protocol=y("protocol");e.username=y("username");e.password=y("password");e.hostname=y("hostname");e.port=y("port");e.query=p("query","?");e.fragment=p("fragment","#");e.search=function(a,b){var d=this.query(a,b);return"string"===typeof d&&d.length?"?"+d:d};e.hash=function(a,b){var d=
this.fragment(a,b);return"string"===typeof d&&d.length?"#"+d:d};e.pathname=function(a,b){if(void 0===a||!0===a){var d=this._parts.path||(this._parts.hostname?"/":"");return a?(this._parts.urn?c.decodeUrnPath:c.decodePath)(d):d}this._parts.path=this._parts.urn?a?c.recodeUrnPath(a):"":a?c.recodePath(a):"/";this.build(!b);return this};e.path=e.pathname;e.href=function(a,b){var d;if(void 0===a)return this.toString();this._string="";this._parts=c._parts();var k=a instanceof c,e="object"===typeof a&&(a.hostname||
a.path||a.pathname);a.nodeName&&(e=c.getDomAttribute(a),a=a[e]||"",e=!1);!k&&e&&void 0!==a.pathname&&(a=a.toString());if("string"===typeof a||a instanceof String)this._parts=c.parse(String(a),this._parts);else if(k||e)for(d in k=k?a._parts:a,k)v.call(this._parts,d)&&(this._parts[d]=k[d]);else throw new TypeError("invalid input");this.build(!b);return this};e.is=function(a){var b=!1,d=!1,k=!1,e=!1,g=!1,f=!1,r=!1,m=!this._parts.urn;this._parts.hostname&&(m=!1,d=c.ip4_expression.test(this._parts.hostname),
k=c.ip6_expression.test(this._parts.hostname),b=d||k,g=(e=!b)&&q&&q.has(this._parts.hostname),f=e&&c.idn_expression.test(this._parts.hostname),r=e&&c.punycode_expression.test(this._parts.hostname));switch(a.toLowerCase()){case "relative":return m;case "absolute":return!m;case "domain":case "name":return e;case "sld":return g;case "ip":return b;case "ip4":case "ipv4":case "inet4":return d;case "ip6":case "ipv6":case "inet6":return k;case "idn":return f;case "url":return!this._parts.urn;case "urn":return!!this._parts.urn;
case "punycode":return r}return null};var E=e.protocol,F=e.port,G=e.hostname;e.protocol=function(a,b){if(void 0!==a&&a&&(a=a.replace(/:(\/\/)?$/,""),!a.match(c.protocol_expression)))throw new TypeError('Protocol "'+a+"\" contains characters other than [A-Z0-9.+-] or doesn't start with [A-Z]");return E.call(this,a,b)};e.scheme=e.protocol;e.port=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0!==a&&(0===a&&(a=null),a&&(a+="",":"===a.charAt(0)&&(a=a.substring(1)),a.match(/[^0-9]/))))throw new TypeError('Port "'+
a+'" contains characters other than [0-9]');return F.call(this,a,b)};e.hostname=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0!==a){var d={};if("/"!==c.parseHost(a,d))throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-]');a=d.hostname}return G.call(this,a,b)};e.host=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a)return this._parts.hostname?c.buildHost(this._parts):"";if("/"!==c.parseHost(a,this._parts))throw new TypeError('Hostname "'+
a+'" contains characters other than [A-Z0-9.-]');this.build(!b);return this};e.authority=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a)return this._parts.hostname?c.buildAuthority(this._parts):"";if("/"!==c.parseAuthority(a,this._parts))throw new TypeError('Hostname "'+a+'" contains characters other than [A-Z0-9.-]');this.build(!b);return this};e.userinfo=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a){if(!this._parts.username)return"";var d=c.buildUserinfo(this._parts);
return d.substring(0,d.length-1)}"@"!==a[a.length-1]&&(a+="@");c.parseUserinfo(a,this._parts);this.build(!b);return this};e.resource=function(a,b){var d;if(void 0===a)return this.path()+this.search()+this.hash();d=c.parse(a);this._parts.path=d.path;this._parts.query=d.query;this._parts.fragment=d.fragment;this.build(!b);return this};e.subdomain=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";var d=this._parts.hostname.length-
this.domain().length-1;return this._parts.hostname.substring(0,d)||""}d=this._parts.hostname.length-this.domain().length;d=this._parts.hostname.substring(0,d);d=new RegExp("^"+x(d));a&&"."!==a.charAt(a.length-1)&&(a+=".");a&&c.ensureValidHostname(a);this._parts.hostname=this._parts.hostname.replace(d,a);this.build(!b);return this};e.domain=function(a,b){if(this._parts.urn)return void 0===a?"":this;"boolean"===typeof a&&(b=a,a=void 0);if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";
var d=this._parts.hostname.match(/\./g);if(d&&2>d.length)return this._parts.hostname;d=this._parts.hostname.length-this.tld(b).length-1;d=this._parts.hostname.lastIndexOf(".",d-1)+1;return this._parts.hostname.substring(d)||""}if(!a)throw new TypeError("cannot set domain empty");c.ensureValidHostname(a);!this._parts.hostname||this.is("IP")?this._parts.hostname=a:(d=new RegExp(x(this.domain())+"$"),this._parts.hostname=this._parts.hostname.replace(d,a));this.build(!b);return this};e.tld=function(a,
b){if(this._parts.urn)return void 0===a?"":this;"boolean"===typeof a&&(b=a,a=void 0);if(void 0===a){if(!this._parts.hostname||this.is("IP"))return"";var d=this._parts.hostname.lastIndexOf("."),d=this._parts.hostname.substring(d+1);return!0!==b&&q&&q.list[d.toLowerCase()]?q.get(this._parts.hostname)||d:d}if(a)if(a.match(/[^a-zA-Z0-9-]/))if(q&&q.is(a))d=new RegExp(x(this.tld())+"$"),this._parts.hostname=this._parts.hostname.replace(d,a);else throw new TypeError('TLD "'+a+'" contains characters other than [A-Z0-9]');
else{if(!this._parts.hostname||this.is("IP"))throw new ReferenceError("cannot set TLD on non-domain host");d=new RegExp(x(this.tld())+"$");this._parts.hostname=this._parts.hostname.replace(d,a)}else throw new TypeError("cannot set TLD empty");this.build(!b);return this};e.directory=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path&&!this._parts.hostname)return"";if("/"===this._parts.path)return"/";var d=this._parts.path.length-this.filename().length-
1,d=this._parts.path.substring(0,d)||(this._parts.hostname?"/":"");return a?c.decodePath(d):d}d=this._parts.path.length-this.filename().length;d=this._parts.path.substring(0,d);d=new RegExp("^"+x(d));this.is("relative")||(a||(a="/"),"/"!==a.charAt(0)&&(a="/"+a));a&&"/"!==a.charAt(a.length-1)&&(a+="/");a=c.recodePath(a);this._parts.path=this._parts.path.replace(d,a);this.build(!b);return this};e.filename=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path||
"/"===this._parts.path)return"";var d=this._parts.path.lastIndexOf("/"),d=this._parts.path.substring(d+1);return a?c.decodePathSegment(d):d}d=!1;"/"===a.charAt(0)&&(a=a.substring(1));a.match(/\.?\//)&&(d=!0);var e=new RegExp(x(this.filename())+"$");a=c.recodePath(a);this._parts.path=this._parts.path.replace(e,a);d?this.normalizePath(b):this.build(!b);return this};e.suffix=function(a,b){if(this._parts.urn)return void 0===a?"":this;if(void 0===a||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";
var d=this.filename(),e=d.lastIndexOf(".");if(-1===e)return"";d=d.substring(e+1);d=/^[a-z0-9%]+$/i.test(d)?d:"";return a?c.decodePathSegment(d):d}"."===a.charAt(0)&&(a=a.substring(1));if(d=this.suffix())e=a?new RegExp(x(d)+"$"):new RegExp(x("."+d)+"$");else{if(!a)return this;this._parts.path+="."+c.recodePath(a)}e&&(a=c.recodePath(a),this._parts.path=this._parts.path.replace(e,a));this.build(!b);return this};e.segment=function(a,b,d){var c=this._parts.urn?":":"/",e=this.path(),g="/"===e.substring(0,
1),e=e.split(c);void 0!==a&&"number"!==typeof a&&(d=b,b=a,a=void 0);if(void 0!==a&&"number"!==typeof a)throw Error('Bad segment "'+a+'", must be 0-based integer');g&&e.shift();0>a&&(a=Math.max(e.length+a,0));if(void 0===b)return void 0===a?e:e[a];if(null===a||void 0===e[a])if(l(b)){e=[];a=0;for(var f=b.length;a<f;a++)if(b[a].length||e.length&&e[e.length-1].length)e.length&&!e[e.length-1].length&&e.pop(),e.push(b[a])}else{if(b||"string"===typeof b)""===e[e.length-1]?e[e.length-1]=b:e.push(b)}else b?
e[a]=b:e.splice(a,1);g&&e.unshift("");return this.path(e.join(c),d)};e.segmentCoded=function(a,b,d){var e,g;"number"!==typeof a&&(d=b,b=a,a=void 0);if(void 0===b){a=this.segment(a,b,d);if(l(a))for(e=0,g=a.length;e<g;e++)a[e]=c.decode(a[e]);else a=void 0!==a?c.decode(a):void 0;return a}if(l(b))for(e=0,g=b.length;e<g;e++)b[e]=c.encode(b[e]);else b="string"===typeof b||b instanceof String?c.encode(b):b;return this.segment(a,b,d)};var H=e.query;e.query=function(a,b){if(!0===a)return c.parseQuery(this._parts.query,
this._parts.escapeQuerySpace);if("function"===typeof a){var d=c.parseQuery(this._parts.query,this._parts.escapeQuerySpace),e=a.call(this,d);this._parts.query=c.buildQuery(e||d,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);this.build(!b);return this}return void 0!==a&&"string"!==typeof a?(this._parts.query=c.buildQuery(a,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace),this.build(!b),this):H.call(this,a,b)};e.setQuery=function(a,b,d){var e=c.parseQuery(this._parts.query,
this._parts.escapeQuerySpace);if("string"===typeof a||a instanceof String)e[a]=void 0!==b?b:null;else if("object"===typeof a)for(var g in a)v.call(a,g)&&(e[g]=a[g]);else throw new TypeError("URI.addQuery() accepts an object, string as the name parameter");this._parts.query=c.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);"string"!==typeof a&&(d=b);this.build(!d);return this};e.addQuery=function(a,b,d){var e=c.parseQuery(this._parts.query,this._parts.escapeQuerySpace);
c.addQuery(e,a,void 0===b?null:b);this._parts.query=c.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);"string"!==typeof a&&(d=b);this.build(!d);return this};e.removeQuery=function(a,b,d){var e=c.parseQuery(this._parts.query,this._parts.escapeQuerySpace);c.removeQuery(e,a,b);this._parts.query=c.buildQuery(e,this._parts.duplicateQueryParameters,this._parts.escapeQuerySpace);"string"!==typeof a&&(d=b);this.build(!d);return this};e.hasQuery=function(a,b,d){var e=c.parseQuery(this._parts.query,
this._parts.escapeQuerySpace);return c.hasQuery(e,a,b,d)};e.setSearch=e.setQuery;e.addSearch=e.addQuery;e.removeSearch=e.removeQuery;e.hasSearch=e.hasQuery;e.normalize=function(){return this._parts.urn?this.normalizeProtocol(!1).normalizePath(!1).normalizeQuery(!1).normalizeFragment(!1).build():this.normalizeProtocol(!1).normalizeHostname(!1).normalizePort(!1).normalizePath(!1).normalizeQuery(!1).normalizeFragment(!1).build()};e.normalizeProtocol=function(a){"string"===typeof this._parts.protocol&&
(this._parts.protocol=this._parts.protocol.toLowerCase(),this.build(!a));return this};e.normalizeHostname=function(a){this._parts.hostname&&(this.is("IDN")&&f?this._parts.hostname=f.toASCII(this._parts.hostname):this.is("IPv6")&&n&&(this._parts.hostname=n.best(this._parts.hostname)),this._parts.hostname=this._parts.hostname.toLowerCase(),this.build(!a));return this};e.normalizePort=function(a){"string"===typeof this._parts.protocol&&this._parts.port===c.defaultPorts[this._parts.protocol]&&(this._parts.port=
null,this.build(!a));return this};e.normalizePath=function(a){var b=this._parts.path;if(!b)return this;if(this._parts.urn)return this._parts.path=c.recodeUrnPath(this._parts.path),this.build(!a),this;if("/"===this._parts.path)return this;var d,e="",g,f;"/"!==b.charAt(0)&&(d=!0,b="/"+b);if("/.."===b.slice(-3)||"/."===b.slice(-2))b+="/";b=b.replace(/(\/(\.\/)+)|(\/\.$)/g,"/").replace(/\/{2,}/g,"/");d&&(e=b.substring(1).match(/^(\.\.\/)+/)||"")&&(e=e[0]);for(;;){g=b.indexOf("/..");if(-1===g)break;else if(0===
g){b=b.substring(3);continue}f=b.substring(0,g).lastIndexOf("/");-1===f&&(f=g);b=b.substring(0,f)+b.substring(g+3)}d&&this.is("relative")&&(b=e+b.substring(1));b=c.recodePath(b);this._parts.path=b;this.build(!a);return this};e.normalizePathname=e.normalizePath;e.normalizeQuery=function(a){"string"===typeof this._parts.query&&(this._parts.query.length?this.query(c.parseQuery(this._parts.query,this._parts.escapeQuerySpace)):this._parts.query=null,this.build(!a));return this};e.normalizeFragment=function(a){this._parts.fragment||
(this._parts.fragment=null,this.build(!a));return this};e.normalizeSearch=e.normalizeQuery;e.normalizeHash=e.normalizeFragment;e.iso8859=function(){var a=c.encode,b=c.decode;c.encode=escape;c.decode=decodeURIComponent;try{this.normalize()}finally{c.encode=a,c.decode=b}return this};e.unicode=function(){var a=c.encode,b=c.decode;c.encode=A;c.decode=unescape;try{this.normalize()}finally{c.encode=a,c.decode=b}return this};e.readable=function(){var a=this.clone();a.username("").password("").normalize();
var b="";a._parts.protocol&&(b+=a._parts.protocol+"://");a._parts.hostname&&(a.is("punycode")&&f?(b+=f.toUnicode(a._parts.hostname),a._parts.port&&(b+=":"+a._parts.port)):b+=a.host());a._parts.hostname&&a._parts.path&&"/"!==a._parts.path.charAt(0)&&(b+="/");b+=a.path(!0);if(a._parts.query){for(var d="",e=0,g=a._parts.query.split("&"),r=g.length;e<r;e++){var m=(g[e]||"").split("="),d=d+("&"+c.decodeQuery(m[0],this._parts.escapeQuerySpace).replace(/&/g,"%26"));void 0!==m[1]&&(d+="="+c.decodeQuery(m[1],
this._parts.escapeQuerySpace).replace(/&/g,"%26"))}b+="?"+d.substring(1)}return b+=c.decodeQuery(a.hash(),!0)};e.absoluteTo=function(a){var b=this.clone(),d=["protocol","username","password","hostname","port"],e,g;if(this._parts.urn)throw Error("URNs do not have any generally defined hierarchical components");a instanceof c||(a=new c(a));b._parts.protocol||(b._parts.protocol=a._parts.protocol);if(this._parts.hostname)return b;for(e=0;g=d[e];e++)b._parts[g]=a._parts[g];b._parts.path?".."===b._parts.path.substring(-2)&&
(b._parts.path+="/"):(b._parts.path=a._parts.path,b._parts.query||(b._parts.query=a._parts.query));"/"!==b.path().charAt(0)&&(d=(d=a.directory())?d:0===a.path().indexOf("/")?"/":"",b._parts.path=(d?d+"/":"")+b._parts.path,b.normalizePath());b.build();return b};e.relativeTo=function(a){var b=this.clone().normalize(),d,e,g;if(b._parts.urn)throw Error("URNs do not have any generally defined hierarchical components");a=(new c(a)).normalize();d=b._parts;e=a._parts;g=b.path();a=a.path();if("/"!==g.charAt(0))throw Error("URI is already relative");
if("/"!==a.charAt(0))throw Error("Cannot calculate a URI relative to another relative URI");d.protocol===e.protocol&&(d.protocol=null);if(d.username===e.username&&d.password===e.password&&null===d.protocol&&null===d.username&&null===d.password&&d.hostname===e.hostname&&d.port===e.port)d.hostname=null,d.port=null;else return b.build();if(g===a)return d.path="",b.build();g=c.commonPath(g,a);if(!g)return b.build();e=e.path.substring(g.length).replace(/[^\/]*$/,"").replace(/.*?\//g,"../");d.path=e+d.path.substring(g.length)||
"./";return b.build()};e.equals=function(a){var b=this.clone();a=new c(a);var d={},e={},g={},f;b.normalize();a.normalize();if(b.toString()===a.toString())return!0;d=b.query();e=a.query();b.query("");a.query("");if(b.toString()!==a.toString()||d.length!==e.length)return!1;d=c.parseQuery(d,this._parts.escapeQuerySpace);e=c.parseQuery(e,this._parts.escapeQuerySpace);for(f in d)if(v.call(d,f)){if(!l(d[f])){if(d[f]!==e[f])return!1}else if(!z(d[f],e[f]))return!1;g[f]=!0}for(f in e)if(v.call(e,f)&&!g[f])return!1;
return!0};e.duplicateQueryParameters=function(a){this._parts.duplicateQueryParameters=!!a;return this};e.escapeQuerySpace=function(a){this._parts.escapeQuerySpace=!!a;return this};return c});
(function(f,n){"object"===typeof exports?module.exports=n(require("./URI")):"function"===typeof define&&define.amd?define(["./URI"],n):f.URITemplate=n(f.URI,f)})(this,function(f,n){function q(c){if(q._cache[c])return q._cache[c];if(!(this instanceof q))return new q(c);this.expression=c;q._cache[c]=this;return this}function t(c){this.data=c;this.cache={}}var c=n&&n.URITemplate,x=Object.prototype.hasOwnProperty,h=q.prototype,l={"":{prefix:"",separator:",",named:!1,empty_name_separator:!1,encode:"encode"},
"+":{prefix:"",separator:",",named:!1,empty_name_separator:!1,encode:"encodeReserved"},"#":{prefix:"#",separator:",",named:!1,empty_name_separator:!1,encode:"encodeReserved"},".":{prefix:".",separator:".",named:!1,empty_name_separator:!1,encode:"encode"},"/":{prefix:"/",separator:"/",named:!1,empty_name_separator:!1,encode:"encode"},";":{prefix:";",separator:";",named:!0,empty_name_separator:!1,encode:"encode"},"?":{prefix:"?",separator:"&",named:!0,empty_name_separator:!0,encode:"encode"},"&":{prefix:"&",
separator:"&",named:!0,empty_name_separator:!0,encode:"encode"}};q._cache={};q.EXPRESSION_PATTERN=/\{([^a-zA-Z0-9%_]?)([^\}]+)(\}|$)/g;q.VARIABLE_PATTERN=/^([^*:]+)((\*)|:(\d+))?$/;q.VARIABLE_NAME_PATTERN=/[^a-zA-Z0-9%_]/;q.expand=function(c,f){var z=l[c.operator],n=z.named?"Named":"Unnamed",A=c.variables,y=[],p,m,e;for(e=0;m=A[e];e++)p=f.get(m.name),p.val.length?y.push(q["expand"+n](p,z,m.explode,m.explode&&z.separator||",",m.maxlength,m.name)):p.type&&y.push("");return y.length?z.prefix+y.join(z.separator):
""};q.expandNamed=function(c,r,q,n,l,y){var p="",m=r.encode;r=r.empty_name_separator;var e=!c[m].length,v=2===c.type?"":f[m](y),u,h,t;h=0;for(t=c.val.length;h<t;h++)l?(u=f[m](c.val[h][1].substring(0,l)),2===c.type&&(v=f[m](c.val[h][0].substring(0,l)))):e?(u=f[m](c.val[h][1]),2===c.type?(v=f[m](c.val[h][0]),c[m].push([v,u])):c[m].push([void 0,u])):(u=c[m][h][1],2===c.type&&(v=c[m][h][0])),p&&(p+=n),q?p+=v+(r||u?"=":"")+u:(h||(p+=f[m](y)+(r||u?"=":"")),2===c.type&&(p+=v+","),p+=u);return p};q.expandUnnamed=
function(c,r,q,n,l){var h="",p=r.encode;r=r.empty_name_separator;var m=!c[p].length,e,v,u,t;u=0;for(t=c.val.length;u<t;u++)l?v=f[p](c.val[u][1].substring(0,l)):m?(v=f[p](c.val[u][1]),c[p].push([2===c.type?f[p](c.val[u][0]):void 0,v])):v=c[p][u][1],h&&(h+=n),2===c.type&&(e=l?f[p](c.val[u][0].substring(0,l)):c[p][u][0],h+=e,h=q?h+(r||v?"=":""):h+","),h+=v;return h};q.noConflict=function(){n.URITemplate===q&&(n.URITemplate=c);return q};h.expand=function(c){var f="";this.parts&&this.parts.length||this.parse();
c instanceof t||(c=new t(c));for(var h=0,l=this.parts.length;h<l;h++)f+="string"===typeof this.parts[h]?this.parts[h]:q.expand(this.parts[h],c);return f};h.parse=function(){var c=this.expression,f=q.EXPRESSION_PATTERN,h=q.VARIABLE_PATTERN,n=q.VARIABLE_NAME_PATTERN,t=[],x=0,p,m,e;for(f.lastIndex=0;;){m=f.exec(c);if(null===m){t.push(c.substring(x));break}else t.push(c.substring(x,m.index)),x=m.index+m[0].length;if(!l[m[1]])throw Error('Unknown Operator "'+m[1]+'" in "'+m[0]+'"');if(!m[3])throw Error('Unclosed Expression "'+
m[0]+'"');p=m[2].split(",");for(var v=0,u=p.length;v<u;v++){e=p[v].match(h);if(null===e)throw Error('Invalid Variable "'+p[v]+'" in "'+m[0]+'"');if(e[1].match(n))throw Error('Invalid Variable Name "'+e[1]+'" in "'+m[0]+'"');p[v]={name:e[1],explode:!!e[3],maxlength:e[4]&&parseInt(e[4],10)}}if(!p.length)throw Error('Expression Missing Variable(s) "'+m[0]+'"');t.push({expression:m[0],operator:m[1],variables:p})}t.length||t.push(c);this.parts=t;return this};t.prototype.get=function(c){var f=this.data,
h={type:0,val:[],encode:[],encodeReserved:[]},l;if(void 0!==this.cache[c])return this.cache[c];this.cache[c]=h;f="[object Function]"===String(Object.prototype.toString.call(f))?f(c):"[object Function]"===String(Object.prototype.toString.call(f[c]))?f[c](c):f[c];if(void 0!==f&&null!==f)if("[object Array]"===String(Object.prototype.toString.call(f))){l=0;for(c=f.length;l<c;l++)void 0!==f[l]&&null!==f[l]&&h.val.push([void 0,String(f[l])]);h.val.length&&(h.type=3)}else if("[object Object]"===String(Object.prototype.toString.call(f))){for(l in f)x.call(f,
l)&&void 0!==f[l]&&null!==f[l]&&h.val.push([l,String(f[l])]);h.val.length&&(h.type=2)}else h.type=1,h.val.push([void 0,String(f)]);return h};f.expand=function(c,h){var l=(new q(c)).expand(h);return new f(l)};return q});
(function(f,n){"object"===typeof exports?module.exports=n(require("./URI")):"function"===typeof define&&define.amd?define(["./URI"],n):n(f.URI)})(this,function(f){var n=f.prototype,q=n.fragment;f.fragmentPrefix="?";var t=f._parts;f._parts=function(){var c=t();c.fragmentPrefix=f.fragmentPrefix;return c};n.fragmentPrefix=function(c){this._parts.fragmentPrefix=c;return this};n.fragment=function(c,n){var h=this._parts.fragmentPrefix,l=this._parts.fragment||"";return!0===c?l.substring(0,h.length)!==h?
{}:f.parseQuery(l.substring(h.length)):void 0!==c&&"string"!==typeof c?(this._parts.fragment=h+f.buildQuery(c),this.build(!n),this):q.call(this,c,n)};n.addFragment=function(c,n,h){var l=this._parts.fragmentPrefix,g=f.parseQuery((this._parts.fragment||"").substring(l.length));f.addQuery(g,c,n);this._parts.fragment=l+f.buildQuery(g);"string"!==typeof c&&(h=n);this.build(!h);return this};n.removeFragment=function(c,n,h){var l=this._parts.fragmentPrefix,g=f.parseQuery((this._parts.fragment||"").substring(l.length));
f.removeQuery(g,c,n);this._parts.fragment=l+f.buildQuery(g);"string"!==typeof c&&(h=n);this.build(!h);return this};n.addHash=n.addFragment;n.removeHash=n.removeFragment;return f});
